# Generated by Django 3.1.6 on 2021-03-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_profile',
        ),
    ]
