# Generated by Django 3.1.6 on 2021-03-07 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210307_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
