# Generated by Django 3.1.6 on 2021-03-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_exerciseplan_minutes_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplan',
            name='minutes_needed',
            field=models.IntegerField(default=0),
        ),
    ]
