# Generated by Django 3.1.6 on 2021-03-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210305_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseplan',
            old_name='minutes_needed',
            new_name='main_exercise_time',
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='cooldown_instructions',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='cooldown_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='warmup_instructions',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='warmup_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
